
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.4 EDK_MS4.81d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhwicap.h"

/*
* The configuration table for devices
*/

XHwIcap_Config XHwIcap_ConfigTable[] =
{
	{
		XPAR_XPS_HWICAP_0_DEVICE_ID,
		XPAR_XPS_HWICAP_0_BASEADDR
	}
};


